version: 2.1
orbs:
  slack: circleci/slack@3.4.2
  gh-pages: sugarshin/gh-pages@0.0.6
workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - stable
                - v0.3.3
                - sigmod2014contest
                - gh-pages

jobs:
  test:
    resource_class: xlarge
    working_directory: ~/ldbc/ldbc_snb_datagen
    machine:
      image: ubuntu-2004:202008-01

    steps:
      - checkout
      - run: |
          DEBIAN_FRONTEND=noninteractive
          sudo apt update
          sudo apt install -y openjdk-8-jdk
          sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-8-openjdk-amd64/bin/java 1
          sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/bin/java
          java -version
      - run: mvn -ntp test
      - run: docker build . -t ldbc/spark
      - run: |
          mkdir dist/
          # deploy CircleCI configuration provide 'filters' instructions (and prevent failed build on gh-pages)
          cp -r .circleci dist/
          sed 's/:1$/:0.1/g' params-csv-basic.ini > params.ini
          tools/run.sh
          sed 's/:1$/:0.1/g' params-csv-composite.ini > params.ini
          tools/run.sh
          sed 's/:1$/:0.1/g' params-csv-merge-foreign.ini > params.ini
          tools/run.sh
          sed 's/:1$/:0.1/g' params-csv-composite-merge-foreign.ini > params.ini
          tools/run.sh


      - gh-pages/deploy:
          ssh-fingerprints: '60:8f:35:48:99:c0:ae:9f:71:6b:a9:66:19:21:95:7d'
      - slack/status
